[project]
name = "primitive-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Petr", email = "you@example.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
primitive-db = "primitive_db:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
